/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Renta.Utemita.Presentacion;

import Renta.Utemita.ServicioBD.AccesoBD;
import javax.swing.JOptionPane;

/**
 *
 * @author kAarl
 */
public class VentanaIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaIniciarSesion
     */
    private String correo;
    private String password;
    AccesoBD conexionBD=new AccesoBD();
    public VentanaIniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloCorreo = new java.awt.Label();
        tituloPassword = new java.awt.Label();
        correoInicioSesion = new javax.swing.JTextField();
        passwordInicioSesion = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();
        jLabelInicioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCorreo.setBackground(new java.awt.Color(255, 255, 255));
        tituloCorreo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tituloCorreo.setText("Ingrese su correo");
        jPanel1.add(tituloCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 780, 30));

        tituloPassword.setBackground(new java.awt.Color(255, 255, 255));
        tituloPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tituloPassword.setText("Password");
        jPanel1.add(tituloPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 770, 30));

        correoInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        correoInicioSesion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        correoInicioSesion.setDoubleBuffered(true);
        correoInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(correoInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 810, 110));

        passwordInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(passwordInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 790, 100));

        botonIniciarSesion.setBackground(new java.awt.Color(204, 255, 204));
        botonIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonIniciarSesion.setText("Iniciar Sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 250, 100));

        jLabelInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/living-room-g524bf7a6f_1920.jpg"))); // NOI18N
        jPanel1.add(jLabelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        // TODO add your handling code here:
         conexionBD.iniciarBD();
        //leer datos ingresados por el usuario
        correo=correoInicioSesion.getText();
        password=passwordInicioSesion.getText();
        System.out.println(correo+password);
        //llamar a la consulta de existeUsuairo
        //si existe accede al programa sino muestra alerta
        if((conexionBD.existeUsuario(correo, password))==true){
            System.out.println("A ingresado a la aplicacion");
            VentanaMenuPrincipal ventanaMenuPrincipal=new VentanaMenuPrincipal();
            ventanaMenuPrincipal.setBounds(0, 0, 1920, 1080);
            ventanaMenuPrincipal.setVisible(true);
        }
        else{
            System.out.println("No ingreso a la BD");
            JOptionPane.showMessageDialog(null,"Correo o Password invalidos");
        }
        //termina la conexion de la base de datos
        conexionBD.DesconectarBD();   
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void correoInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    public javax.swing.JTextField correoInicioSesion;
    private javax.swing.JLabel jLabelInicioSesion;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField passwordInicioSesion;
    private java.awt.Label tituloCorreo;
    private java.awt.Label tituloPassword;
    // End of variables declaration//GEN-END:variables
}
